# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicCloud' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicCloud
	pod 'Alamofire'
	pod 'Realm'
	pod 'RealmSwift'
	pod 'ESTabBarController-swift'
	pod 'Kingfisher'
	pod 'BmoViewPager'
	pod 'XLPagerTabStrip'
	pod 'AlamofireObjectMapper'
end
